import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './nav'
import CSS from 'csstype';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(
  { children, }: { children: React.ReactNode }) {
  const bg_style: CSS.Properties = {
    backgroundColor: 'rgba(255, 255, 255, 0.23)',
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
